# coding: utf-8

"""
    Skillberry Tools Agent

    Skillberry Tools Agent API

    The version of the OpenAPI document: g23ec63f
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skillberry_agent_sdk.api.chat_api import ChatApi


class TestChatApi(unittest.TestCase):
    """ChatApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ChatApi()

    def tearDown(self) -> None:
        pass

    def test_api_chat_completion_chat_completions_post(self) -> None:
        """Test case for api_chat_completion_chat_completions_post

        Api Chat Completion
        """
        pass

    def test_api_chat_completion_v1_chat_completions_post(self) -> None:
        """Test case for api_chat_completion_v1_chat_completions_post

        Api Chat Completion
        """
        pass

    def test_api_prompt_prompt_post(self) -> None:
        """Test case for api_prompt_prompt_post

        Api Prompt
        """
        pass


if __name__ == '__main__':
    unittest.main()
