# coding: utf-8

"""
    Skillberry Tools Agent

    Skillberry Tools Agent API

    The version of the OpenAPI document: g23ec63f
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skillberry_agent_sdk.models.chat_request import ChatRequest

class TestChatRequest(unittest.TestCase):
    """ChatRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChatRequest:
        """Test ChatRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChatRequest`
        """
        model = ChatRequest()
        if include_optional:
            return ChatRequest(
                model = '',
                messages = [
                    skillberry_agent_sdk.models.chat_message.ChatMessage(
                        role = '', 
                        content = '', )
                    ],
                temperature = 0.0,
                max_tokens = 0.0
            )
        else:
            return ChatRequest(
                model = '',
                messages = [
                    skillberry_agent_sdk.models.chat_message.ChatMessage(
                        role = '', 
                        content = '', )
                    ],
        )
        """

    def testChatRequest(self):
        """Test ChatRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
