# coding: utf-8

"""
    Skillberry Tools Agent

    Skillberry Tools Agent API

    The version of the OpenAPI document: g23ec63f
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skillberry_agent_sdk.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_api_disconnect_disconnect_post(self) -> None:
        """Test case for api_disconnect_disconnect_post

        Api Disconnect
        """
        pass

    def test_get_trajectory_trajectory_get(self) -> None:
        """Test case for get_trajectory_trajectory_get

        Get Trajectory
        """
        pass

    def test_health_check_health_get(self) -> None:
        """Test case for health_check_health_get

        Health Check
        """
        pass

    def test_health_check_version_get(self) -> None:
        """Test case for health_check_version_get

        Health Check
        """
        pass


if __name__ == '__main__':
    unittest.main()
